name: Update Data

on:
  push:
    paths:
      - 'data.json'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update data file
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data.json
        git commit -m "Update data file" || echo "No changes to commit"
        git push